# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor', '0001_initial'),
        ('login', '0001_initial'),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='startups',
            field=models.ManyToManyField(blank=True, null=True, to='startup.Startup'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Type'),
        ),
    ]
