# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_auto_20190214_0906'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='startups',
            field=models.OneToOneField(blank=True, default=9, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup'),
            preserve_default=False,
        ),
    ]
