# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.FileField(default='profile_photos/default.jpg', upload_to='profile_photos/'),
        ),
    ]
