# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup', '0016_auto_20190214_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents/')),
                ('typ', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=100, null=True)),
                ('ppt', models.FileField(upload_to='documents/')),
                ('accept', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('accept', models.BooleanField(default=False)),
                ('ppt', models.FileField(upload_to='documents/')),
                ('clicked', models.BooleanField(default=False)),
                ('ddip', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=1000, null=True)),
                ('schedule', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
