# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
