# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0015_startup_user'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup'),
        ),
    ]
