# -*- coding: utf-8 -*-
<<<<<<< HEAD:Startup_incubator/administrator/migrations/0002_fund_startup.py
# Generated by Django 1.10 on 2019-02-14 22:52
=======
# Generated by Django 1.10 on 2019-02-14 23:01
>>>>>>> b6c30bbd7461d63d95361589577146c535b5bb6d:Startup_incubator/administrator/migrations/0003_fund_startup.py
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0015_startup_user'),
<<<<<<< HEAD:Startup_incubator/administrator/migrations/0002_fund_startup.py
        ('administrator', '0001_initial'),
=======
        ('administrator', '0002_incubation_startup'),
>>>>>>> b6c30bbd7461d63d95361589577146c535b5bb6d:Startup_incubator/administrator/migrations/0003_fund_startup.py
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup'),
        ),
    ]
