# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startup', '0004_auto_20190216_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100, null=True)),
                ('room_no', models.CharField(max_length=100, null=True)),
                ('paid', models.CharField(max_length=100, null=True)),
                ('curr', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
    ]
