# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
