# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-16 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rent_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='date_alloted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
