# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('investor', '0001_initial'),
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_to_I', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investor.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='Connection_mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_to_M', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incubation_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.FileField(null=True, upload_to='Incubation_ppts/')),
                ('pending', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('dipp', models.BooleanField(default=False)),
                ('image', models.FileField(default='profile_photos/default.jpg', upload_to='profile_photos/')),
                ('dippno', models.CharField(blank=True, max_length=100, null=True)),
                ('cat', models.CharField(blank=True, max_length=100, null=True)),
                ('founder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Founder')),
                ('investors', models.ManyToManyField(blank=True, to='investor.Investor')),
                ('mentors', models.ManyToManyField(blank=True, to='mentor.Mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress')], default='Pending', max_length=500)),
                ('date_assigned', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
        migrations.AddField(
            model_name='incubation_request',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Startup'),
        ),
        migrations.AddField(
            model_name='connection_mentor',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup'),
        ),
        migrations.AddField(
            model_name='connection_investor',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup'),
        ),
    ]
