# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-13 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
        ('mentor', '0001_initial'),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_to_I', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investor.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='Connection_mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_to_M', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor.Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='dipp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='investors',
            field=models.ManyToManyField(blank=True, to='investor.Investor'),
        ),
        migrations.AddField(
            model_name='startup',
            name='mentors',
            field=models.ManyToManyField(blank=True, to='mentor.Mentor'),
        ),
        migrations.AddField(
            model_name='startup',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connection_mentor',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup'),
        ),
        migrations.AddField(
            model_name='connection_investor',
            name='startup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup'),
        ),
    ]
