# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_auto_20190213_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection_investor',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='connection_investor',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='connection_mentor',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='connection_mentor',
            name='startup',
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='Connection_investor',
        ),
        migrations.DeleteModel(
            name='Connection_mentor',
        ),
    ]
