# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_investor_startups'),
        ('mentor', '0003_auto_20190214_0907'),
        ('startup', '0003_auto_20190214_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_to_I', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investor.Investor')),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
        migrations.CreateModel(
            name='Connection_mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_to_M', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor.Mentor')),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
        ),
    ]
