# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0005_startup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Type'),
        ),
    ]
