# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0007_startup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='dippno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
