# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0008_startup_dippno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='founders',
        ),
        migrations.AddField(
            model_name='startup',
            name='founder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startup.Founder'),
        ),
    ]
