# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0009_auto_20190214_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='image',
            field=models.FileField(upload_to='profile_photos/'),
        ),
    ]
