# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0013_auto_20190214_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='user',
        ),
    ]
