# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('startup', '0014_remove_startup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='login.Type'),
            preserve_default=False,
        ),
    ]
