# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='typ',
        ),
    ]
