# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('startup', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('image', models.FileField(default='profile_photos/default.jpg', upload_to='profile_photos/')),
                ('startups', models.ManyToManyField(blank=True, null=True, to='startup.Startup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Type')),
            ],
        ),
    ]
